server:
  port: 9090
zuul:
  routes:
    
    ui:
      path: /**
      url: http://localhost:3000
      stripPrefix: true
      sensitive-headers:
    auth:
      path: /auth/**
      url: http://localhost:8080
      stripPrefix: false
      sensitive-headers:
#    app:
#      path: /api/**
#      url: http://localhost:9091
#      stripPrefix: false
#      sensitive-headers:
    graphql:
      path: /graphql/**
      url: http://localhost:4000
      stripPrefix: false
      sensitive-headers:
  